version: "1"
rules:                      # Array of rules
  - base: main            # Required. Target branch
    upstream: openshift-helm-charts/charts:main    # Required. Must be in the same fork network.
    mergeMethod: hardreset  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: false    # Optional, merge pull request even when the mergeable_state is not clean. Default: false
  - base: sync-fork-and-upstream
    upstream: main        # Required. Can be a branch in the same forked repo.
    assignees:              # Optional
      - openshift-helm-charts-bot
    reviewers:              # Optional
      - openshift-helm-charts-bot
    conflictReviewers:      # Optional, on merge conflict assign a reviewer
      - openshift-helm-charts-bot
    mergeMethod: rebase  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: false    # Optional, merge pull request even when the mergeable_state is not clean. Default: false
label: ":arrow_heading_down: pull"  # Optional
conflictLabel: "sync-conflict"     # Optional, on merge conflict assign a custom label, Default: merge-conflict
